AWSTemplateFormatVersion: 2010-09-09
Description: VaultDB Lambda funtion to execute Queries
Metadata:
  Author: VaultDB.ai
  Url: https://vaultdb.ai
      
Parameters:
  ApplicationName:
    Type: String
    AllowedPattern: "^[a-z][a-z0-9-]{0,48}[a-z0-9]$"
    Description: Enter the name of your application with no spaces.
    
Resources:
  ExecuteRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Join ['', ['vaultdb', '-execution-role-', !Ref ApplicationName]]
      Tags:
        - Key: Purpose
          Value: 'VaultDB'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
          - Effect: Allow
            Principal:
              Service:
                - ecs-tasks.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: !Join ['', ['vaultdb', '-execution-service-policy-', !Ref ApplicationName]]
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                Resource: '*'
              - Effect: Allow
                Action:
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: '*'
              - Effect: Allow
                Action:
                  - s3:ListMultipartUploadParts
                  - s3:*Object
                Resource: '*'
              - Effect: Allow
                Action:
                  - elasticfilesystem:ClientMount
                  - elasticfilesystem:ClientWrite
                Resource: '*'
              - Effect: Allow
                Action:
                  - ec2:DescribeNetworkInterfaces
                  - ec2:CreateNetworkInterface
                  - ec2:DeleteNetworkInterface
                  - ec2:DescribeInstances
                  - ec2:AttachNetworkInterface
                Resource: '*'

  AccessPointResource:
    Type: AWS::EFS::AccessPoint
    Properties:
      FileSystemId: 
        Fn::ImportValue: !Sub '${ApplicationName}-EFSFileSystem'
      PosixUser:
        Uid: 1001
        Gid: 1001
      RootDirectory:
        CreationInfo:
          OwnerGid: 1001
          OwnerUid: 1001
          Permissions: 770
        Path: /commitlog

  ExecuteQueryFunction:
    Type: AWS::Lambda::Function
    Properties:
      Tags:
        - Key: Purpose
          Value: 'VaultDB'    
      Description: Execute Vaultdb SQL Qeries
      FunctionName: !Join ['', ['vaultdb', '-execute-query-', !Ref ApplicationName]]
      Handler: index.lambda_handler
      MemorySize: 128
      Runtime: python3.8
      Role: !GetAtt ExecuteRole.Arn
      Timeout: 240
      Environment:
        Variables:
          commitlog_directory: '/mnt/commitlog'
          data_store: !Join ['', ['vaultdb', '-data-', !Ref ApplicationName]]
      VpcConfig:
        SecurityGroupIds:
          - Fn::ImportValue: !Sub '${ApplicationName}-DataSecurityGroup'
        SubnetIds:
          - Fn::ImportValue: !Sub '${ApplicationName}-VPCPrivateSubnet'
      FileSystemConfigs:
        - Arn: !GetAtt AccessPointResource.Arn
          LocalMountPath: /mnt/commitlog
      Code:
        S3Bucket: !Sub "${ApplicationName}-PublicBucket"
        S3Key: 'release/lambda-package.zip'

Outputs:
  ExecuteRole:
    Description: VaultDB Execution Role that works on behalf of user
    Value: !Ref ExecuteRole
    Export:
      Name: !Sub ${ApplicationName}-ExecuteRole
  CLI:
    Description: Use this command to invoke the Lambda function
    Value: !Sub |
        aws lambda invoke --function-name 'vaultdb-execute-query-${ApplicationName}' --payload 'SELECT CURRENT_CATALOG' lambda-output.txt --cli-binary-format raw-in-base64-out
        