AWSTemplateFormatVersion: "2010-09-09"
Description: VaultDB Create secure S3 bucket to store data

Parameters:
  ApplicationName:
    Type: String
    AllowedPattern: "^[a-z][a-z0-9-]{0,48}[a-z0-9]$"
    Description: Enter the name of your application with no spaces.

Metadata:
  Author: VaultDB.ai
  Url: https://vaultdb.ai

Rules:
  ApplicationNameIsRequired:
    Assertions:
      - AssertDescription: Application Name is required
        Assert: !Not [!Equals [!Ref ApplicationName, ""]]

Resources:
  DataBucket:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName:
        !Join ["", [!Ref ApplicationName, "-data-", !Sub "${AWS::AccountId}"]]
      Tags:
        - Key: Purpose
          Value: "VaultDB"
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256

  PublicBucket:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName:
        !Join [
          "",
          [!Ref ApplicationName, "-public-storage-", !Sub "${AWS::AccountId}"],
        ]
      Tags:
        - Key: Purpose
          Value: "VaultDB"
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      WebsiteConfiguration:
        IndexDocument: "index.html"
        ErrorDocument: "error.html"
      PublicAccessBlockConfiguration:
        BlockPublicPolicy: false

  PublicBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref PublicBucket
      PolicyDocument:
        Id: PublicReadPolicy
        Version: 2012-10-17
        Statement:
          - Sid: PublicReadForGetBucketObjects
            Effect: Allow
            Principal: "*"
            Action: "s3:GetObject"
            Resource: !Sub arn:aws:s3:::${PublicBucket}/*
          - Sid: AddPermlist
            Effect: Allow
            Principal: "*"
            Action: "s3:ListBucket"
            Resource: !Sub arn:aws:s3:::${PublicBucket}

  EFSFileSystem:
    Type: AWS::EFS::FileSystem
    Properties:
      BackupPolicy:
        Status: ENABLED
      Encrypted: true
      LifecyclePolicies:
        - TransitionToIA: AFTER_60_DAYS
      PerformanceMode: generalPurpose
      ThroughputMode: bursting
      FileSystemTags:
        - Key: Purpose
          Value: "VaultDB"
        - Key: Project
          Value: !Ref ApplicationName
        - Key: createdBy
          Value: vaultdb.ai

  EFSMountTarget:
    Type: AWS::EFS::MountTarget
    Properties:
      FileSystemId: !Ref EFSFileSystem
      SecurityGroups:
        - Fn::ImportValue: !Sub "${ApplicationName}-DataSecurityGroup"
      SubnetId:
        Fn::ImportValue: !Sub "${ApplicationName}-VPCPrivateSubnet"

Outputs:
  DataBucketName:
    Description: Name of the main bucket
    Value: !Ref DataBucket
    Export:
      Name: !Sub ${ApplicationName}-DataBucket
  PublicBucket:
    Description: Name of the public bucket
    Value: !Ref PublicBucket
    Export:
      Name: !Sub ${ApplicationName}-PublicBucket
  WebsiteURL:
    Value: !GetAtt PublicBucket.WebsiteURL
    Description: URL for website hosted on S3
    Export:
      Name: !Sub ${ApplicationName}-WebsiteURL
  EFSFileSystem:
    Description: The created EFS
    Value: !Ref EFSFileSystem
    Export:
      Name: !Sub ${ApplicationName}-EFSFileSystem
  EFSMountTarget:
    Description: The EFS EFSMountTarget
    Value: !Ref EFSMountTarget
    Export:
      Name: !Sub ${ApplicationName}-EFSMountTarget
