AWSTemplateFormatVersion: "2010-09-09"
Description: VaultDB Create secure S3 bucket to store data

Parameters:
  ApplicationName:
    Type: String
    AllowedPattern: "^[a-z][a-z0-9-]{0,48}[a-z0-9]$"
    Description: Enter the name of your application with no spaces.

Metadata:
  Author: VaultDB.ai
  Url: https://vaultdb.ai

Rules:
  ApplicationNameIsRequired:
    Assertions:
      - AssertDescription: Application Name is required
        Assert: !Not [!Equals [!Ref ApplicationName, ""]]

Resources:
  DataBucket:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName:
        !Join [
          "",
          [
            "vaultdb",
            "-data-",
            !Sub "${AWS::AccountId}",
            "-",
            !Ref ApplicationName,
          ],
        ]
      Tags:
        - Key: Purpose
          Value: "VaultDB"
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256

  PublicBucket:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName:
        !Join [
          "",
          [
            "vaultdb",
            "-public-storage-",
            !Sub "${AWS::AccountId}",
            "-",
            !Ref ApplicationName,
          ],
        ]
      Tags:
        - Key: Purpose
          Value: "VaultDB"
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      AccessControl: "PublicRead"
      WebsiteConfiguration:
        IndexDocument: "index.html"
        ErrorDocument: "error.html"

  EFSFileSystem:
    Type: AWS::EFS::FileSystem
    Properties:
      BackupPolicy:
        Status: ENABLED
      Encrypted: true
      LifecyclePolicies:
        - TransitionToIA: AFTER_60_DAYS
      PerformanceMode: generalPurpose
      ThroughputMode: bursting
      FileSystemTags:
        - Key: Purpose
          Value: "VaultDB"
        - Key: Project
          Value: !Ref ApplicationName
        - Key: createdBy
          Value: vaultdb.ai

  EFSMountTarget:
    Type: AWS::EFS::MountTarget
    Properties:
      FileSystemId: !Ref EFSFileSystem
      SecurityGroups:
        - Fn::ImportValue: !Sub "${ApplicationName}-DataSecurityGroup"
      SubnetId:
        Fn::ImportValue: !Sub "${ApplicationName}-VPCPrivateSubnet"

Outputs:
  DataBucketName:
    Description: Name of the main bucket
    Value: !Ref DataBucket
    Export:
      Name: !Sub ${ApplicationName}-DataBucket
  PulicBucketName:
    Description: Name of the public bucket
    Value: !Ref PublicBucket
    Export:
      Name: !Sub ${ApplicationName}-PublicBucket
  EFSFileSystem:
    Description: The created EFS
    Value: !Ref EFSFileSystem
    Export:
      Name: !Sub ${ApplicationName}-EFSFileSystem
  EFSMountTarget:
    Description: The EFS EFSMountTarget
    Value: !Ref EFSMountTarget
    Export:
      Name: !Sub ${ApplicationName}-EFSMountTarget
