AWSTemplateFormatVersion: "2010-09-09"
Description: >
  s3 to store VaultDB data permanently.
Parameters:
  VPCState:
    Type: String
    AllowedValues:
      - new
      - existing
    ConstraintDescription: Must state whether there is an existing VPC or not
  Name:
    Type: String
    Description: >-
      The name of the application. 
      This should include a stage qualifier if this is a nonproduction instance.
      Stage qualifiers should only include 3-5 characters
    AllowedPattern: ^[a-z]{3,}(-[a-z]{3,5})?$
    MinLength: 3
  Domain:
    Type: String
    Default: app
    AllowedValues:
      - example.com
      - otherdomain.com
    Description: The domain for the application.
  SigningKeyParameter:
    Type: 'AWS::SSM::Parameter::Name<String>'
    Default: /system/signing-key/default
    Description: >-
      The name of SSM parameter from which to retrieve the cookie signing key
    AllowedValues:
      - /system/signing-key/default
  SigningKeyParameterKeyId:
    Type: String
    Description: >-
      The ID of the KMS key used to encrypt signing key in SSM Parameter Store.
  PrimarySubnetAZ:
    Type: AWS::EC2::AvailabilityZone::Name
    Description: Enter the primary availability zone for your subnet.
  FailoverSubnetAZ:
    Type: AWS::EC2::AvailabilityZone::Name
    Description: Enter the Failover availability zone for your subnet. Please Choose .
  CloudFrontHostedZoneId:
    Type: String
    Default: Z2FDTNDATAQYW2
    AllowedValues:
      - Z2FDTNDATAQYW2
    Description: >-
      The Default Hosted Zone for CloudFront Distributions
    
Mappings:
  VaultDBPlatformMap:
    node:
      version: node-v12
      SolutionStackName: 64bit Amazon Linux 2 v5.0.1 running Node.js 12
    python:
      version: python-v3
      SolutionStackName: 64bit Amazon Linux 2 v3.0.0 running Python 3.7

Conditions:
  IsNewVPC: !Equals [ !Ref VPCState, new ]
  CreateFailoverSubnets: !Not [!Equals [!Ref FailoverSubnetAZ, ""]]

Rules:
  DRandProdCanNotBeSame:
    Assertions:
      - AssertDescription: Primary and Failover availability zone cannot be Same
        Assert: !Not
          - !Ref PrimarySubnetAZ
          - !Ref FailoverSubnetAZ

Resources:
  InfraStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL:
        !Join
          - ''
          - - 'https://s3.amazonaws.com/'
            - !Ref BucketName
            - '/infra.yaml'
      Parameters:
        ApplicationName: !Ref ApplicationName
        SubnetAZ: !Ref SubnetAZ
  RolesStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL:
        !Join
          - ''
          - - 'https://s3.amazonaws.com/'
            - !Ref BucketName
            - '/roles.yaml'
      Parameters:
        ApplicationName: !Ref ApplicationName
        SubnetAZ: !Ref SubnetAZ        
  SqlViewerStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL:
        !Join
          - ''
          - - 'https://s3.amazonaws.com/'
            - !Ref BucketName
            - '/sql_viewer.yaml'
      Parameters:
        ApplicationName: !Ref ApplicationName
        SubnetAZ: !Ref SubnetAZ        
  TaskManagerStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL:
        !Join
          - ''
          - - 'https://s3.amazonaws.com/'
            - !Ref BucketName
            - '/task_manager.yaml'
      Parameters:
        ApplicationName: !Ref ApplicationName
        SubnetAZ: !Ref SubnetAZ        
