AWSTemplateFormatVersion: "2010-09-09"
Description: VaultDB
Parameters:
  PrimarySubnetAZ:
    Type: AWS::EC2::AvailabilityZone::Name
    AllowedPattern: ".+"
    Description: Enter the primary availability zone for your subnet.

  ExistingVpcID:
    Type: String
    Default: ''
    ConstraintDescription: Please enter existing VPC ID to use existing.

  CidrBlock:
    Description: VPC CIDR Block If Creating new (eg 10.0.0.0/16)
    Type: String
    
  PublicSubnetCIDR:
    AllowedPattern: '((\d{1,3})\.){3}\d{1,3}/\d{1,2}'
    Default: 10.0.10.0/24
    Description: VPC CIDR Block for the Public Subnet (eg 10.0.10.0/24)
    Type: String

  PrivateSubnetCIDR:
    AllowedPattern: '((\d{1,3})\.){3}\d{1,3}/\d{1,2}'
    Default: 10.0.20.0/24
    Description: VPC CIDR Block for the Public Subnet (eg 10.0.20.0/24)
    Type: String    

  BucketName:
    Type: String
    Default: 'vaultdb-hosted-content'
    Description: Vaultdb Cloudformation template store. Please do not change unless you have custom templates.

Metadata:
  Author: VaultDB.ai
  Url: https://vaultdb.ai
  AWS::CloudFormation::Interface: 
    ParameterGroups: 
      - 
        Label: 
          default: "Required Parameters"
        Parameters: 
          - PrimarySubnetAZ
          - ExistingVpcID
          - CidrBlock
          - BucketName
        
Conditions:
  IsNewVPC: !Equals [ !Ref ExistingVpcID, '' ]

Rules:
  RequiredParameterAssertions:
    Assertions:
      - AssertDescription: Primary Subnet is required
        Assert: !Not [!Equals [!Ref PrimarySubnetAZ, '']]
      - AssertDescription: Primary Subnet is cannot be empty
        Assert: !Not [!Equals [!Ref PrimarySubnetAZ, '']]
      - AssertDescription: Public Subnet CIDR is required
        Assert: !Not [!Equals [!Ref PublicSubnetCIDR, '']]
      - AssertDescription: Private Subnet CIDR is required
        Assert: !Not [!Equals [!Ref PrivateSubnetCIDR, '']]
  CreateNewVPC:
    RuleCondition: !Equals 
      - !Ref ExistingVpcID
      - ''
    Assertions:        
      - AssertDescription: CidrBlock is required for New VPC.
        Assert: !Not [!Equals [!Ref CidrBlock, '']]

Resources:
  InfraStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL:
        !Join
          - ''
          - - 'https://s3.amazonaws.com/'
            - !Ref BucketName
            - '/awsquickstart/infra/infra.yaml'
      Parameters:
        ApplicationName: !Ref AWS::StackName
        ExistingVpcID: !Ref ExistingVpcID
        CidrBlock: !Ref CidrBlock
        PrimarySubnetAZ: !Ref PrimarySubnetAZ
        PublicSubnetCIDR: !Ref PublicSubnetCIDR
        PrivateSubnetCIDR: !Ref PrivateSubnetCIDR

  RolesStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: InfraStack
    Properties:
      TemplateURL:
        !Join
          - ''
          - - 'https://s3.amazonaws.com/'
            - !Ref BucketName
            - '/awsquickstart/roles/roles.yaml'
      Parameters:
        ApplicationName: !Ref AWS::StackName

  SqlViewerStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: InfraStack
    Properties:
      TemplateURL:
        !Join
          - ''
          - - 'https://s3.amazonaws.com/'
            - !Ref BucketName
            - '/awsquickstart/viewer/viewer.yaml'
      Parameters:
        ApplicationName: !Ref AWS::StackName

  ECSStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: InfraStack
    Properties:
      TemplateURL:
        !Join
          - ''
          - - 'https://s3.amazonaws.com/'
            - !Ref BucketName
            - '/awsquickstart/ecs/tasks.yaml'
      Parameters:
        ApplicationName: !Ref AWS::StackName
