AWSTemplateFormatVersion: "2010-09-09"
Description: VPC Nested stack
Metadata:
  Author: VaultDB.ai
  Url: https://www.vaultdb.ai

Parameters:
  ApplicationName:
    Type: String
    AllowedPattern: "^[a-z][a-z0-9-]{0,48}[a-z0-9]$"
    Description: Enter the name of your application with no spaces.

  CidrBlock:
    # AllowedPattern: '((\d{1,3})\.){3}\d{1,3}/\d{1,2}'
    # Default: 10.0.0.0/16
    Description: VPC CIDR Block (eg 10.0.0.0/16)
    Type: String

  ExistingVpcID:
    Type: String
    Default: ""
    ConstraintDescription: Please Choose existing VPC to use existing

Conditions:
  IsNewVPC: !Equals [!Ref ExistingVpcID, ""]

Rules:
  CreateNewVPC:
    RuleCondition: !Equals
      - !Ref ExistingVpcID
      - ""
    Assertions:
      - AssertDescription: CidrBlock is required
        Assert: !Not [!Equals [!Ref CidrBlock, ""]]

Resources:
  VPC:
    Type: AWS::EC2::VPC
    Condition: IsNewVPC
    Properties:
      CidrBlock: !Ref CidrBlock
      EnableDnsHostnames: true
      Tags:
        - Key: Purpose
          Value: "VaultDB"
        - Key: Name
          Value: !Join ["", [!Ref ApplicationName, "-vpc"]]

Outputs:
  VPC:
    Value: !If
      - IsNewVPC
      - !Ref VPC
      - !Ref ExistingVpcID
    Export:
      Name: !Sub "${ApplicationName}-VPC"
