AWSTemplateFormatVersion: "2010-09-09"
Description: Create EFS volume to store commit log

Parameters:
  ApplicationName:
    Type: String
    AllowedPattern: "^[a-z][a-z0-9-]{0,48}[a-z0-9]$"
    Description: Enter the name of your application with no spaces.

  VPCStackName:
    Type: String
    AllowedPattern: "^[a-z][a-z0-9-]{0,48}[a-z0-9]$"

Metadata:
  Author: VaultDB.ai
  Url: https://vaultdb.ai
  AWS::CloudFormation::Interface: 
    ParameterGroups: 
      - 
        Label: 
          default: "Required Parameters"
        Parameters: 
          - ApplicationName
          - VPCStackName

    ParameterLabels:
      ApplicationName: 
        default: "What are you calling this App(Please Include dev/test/prod in name to diffrentiate between instance)?"
      VPCStackName: 
        default: "What was the name of VPC stack (you should configure network, if not created yet)?"

Rules:
  ApplicationNameIsRequired:
    Assertions:
      - AssertDescription: Application Name is required
        Assert: !Not [!Equals [!Ref ApplicationName, '']]

  VPCStackNameIsRequired:
    Assertions:
      - AssertDescription: VPC Stack name is required
        Assert: !Not [!Equals [!Ref VPCStackName, '']]

Resources:
    EFSSecurityGroup:
        Type: "AWS::EC2::SecurityGroup"
        Properties:
            GroupDescription: "security group for the prod EFS"
            GroupName: !Join ['', [!Ref ApplicationName, '-vaultdb', "-EFS-SG"]]
            VpcId:
              Fn::ImportValue: !Sub "${VPCStackName}-VPC"
            SecurityGroupIngress: 
              - 
                SourceSecurityGroupId: !Join ['', ['sg-', !Ref ApplicationName, 'vaultdb']]
                Description: "servers to connect to efs"
                FromPort: 2049
                IpProtocol: "tcp"
                ToPort: 2049
            Tags:
              - 
                Key: Environment
                Value: !Ref ApplicationName
              - 
                Key: Name
                Value: !Join ['', [!Ref ApplicationName, '-vaultdb', "-VPC-EFS-SG"]]
              - 
                Key: Project
                Value: !Ref ApplicationName
              - 
                Key: createdBy
                Value: vaultdb.ai

    EFSFileSystem:
        Type: AWS::EFS::FileSystem
        Properties:
            BackupPolicy:
              Status: ENABLED
            Encrypted: true
            LifecyclePolicies:
              - TransitionToIA: AFTER_60_DAYS
            PerformanceMode: generalPurpose
            ThroughputMode: bursting
            FileSystemTags: 
              - 
                Key: Environment
                Value: !Ref ApplicationName
              - 
                Key: Name
                Value: !Join ['', [!Ref ApplicationName, '-vaultdb', "-VPC-EFS"]]
              - 
                Key: Project
                Value: !Ref ApplicationName
              - 
                Key: createdBy
                Value: vaultdb.ai

    MountTarget1:
        Type: AWS::EFS::MountTarget
        Properties: 
            FileSystemId: !Ref EFSFileSystem
            IpAddress: "*.*.*.*"
            SecurityGroups: 
              - !Ref EFSSecurityGroup
            SubnetId: 
              Fn::ImportValue: !Sub "${VPCStackName}-VPCPrivateSubnetA"

    EFSInterfaceEndpoint:
        Type: 'AWS::EC2::VPCEndpoint'
        Properties:
            VpcEndpointType: Interface
            ServiceName: !Sub 'com.amazonaws.${AWS::Region}.elasticfilesystem'
            VpcId:
              Fn::ImportValue: !Sub "${VPCStackName}-VPC"
            SubnetIds: 
              Fn::ImportValue: !Sub "${VPCStackName}-VPCPrivateSubnetA"
            SecurityGroupIds:
              - !Ref EFSSecurityGroup
Outputs:
  EFS:
    Description: The created EFS 
    Value: !Ref EFSFileSystem

  EFSMountTarget1:
    Description: The EFS MountTarget1
    Value: !Ref MountTarget1
