AWSTemplateFormatVersion: "2010-09-09"
Description: Create EFS volume to store commit log

Parameters:
  ApplicationName:
    Type: String
    AllowedPattern: "^[a-z][a-z0-9-]{0,48}[a-z0-9]$"
    Description: Enter the name of your application with no spaces.

Metadata:
  Author: VaultDB.ai
  Url: https://vaultdb.ai

Rules:
  ApplicationNameIsRequired:
    Assertions:
      - AssertDescription: Application Name is required
        Assert: !Not [!Equals [!Ref ApplicationName, '']]

Resources:
  EFSSecurityGroup:
      Type: "AWS::EC2::SecurityGroup"
      Properties:
          GroupDescription: "security group for the prod EFS"
          GroupName: !Join ['', ['vaultdb', '-EFS-SG-', !Ref ApplicationName]]
          VpcId:
            Fn::ImportValue: !Sub '${ApplicationName}-VPC'
          Tags:
            - 
              Key: Environment
              Value: !Ref ApplicationName
            - 
              Key: Name
              Value: !Join ['', ['vaultdb', '-VPC-EFS-SG-', !Ref ApplicationName]]
            - 
              Key: Project
              Value: !Ref ApplicationName
            - 
              Key: createdBy
              Value: vaultdb.ai

  EFSSecurityGroupIngress:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
        Description: "Allow EFS to connect to servers and lambda"
        GroupId: !Ref EFSSecurityGroup
        FromPort: 2049
        IpProtocol: "tcp"
        ToPort: 2049

  EFSFileSystem:
      Type: AWS::EFS::FileSystem
      Properties:
          BackupPolicy:
            Status: ENABLED
          Encrypted: true
          LifecyclePolicies:
            - TransitionToIA: AFTER_60_DAYS
          PerformanceMode: generalPurpose
          ThroughputMode: bursting
          FileSystemTags: 
            - 
              Key: Environment
              Value: !Ref ApplicationName
            - 
              Key: Name
              Value: !Join ['', ['vaultdb', '-VPC-EFS-', !Ref ApplicationName]]
            - 
              Key: Project
              Value: !Ref ApplicationName
            - 
              Key: createdBy
              Value: vaultdb.ai

  EFSMountTarget:
      Type: AWS::EFS::MountTarget
      Properties: 
          FileSystemId: !Ref EFSFileSystem
          SecurityGroups: 
            - !Ref EFSSecurityGroup
          SubnetId: 
            Fn::ImportValue: !Sub '${ApplicationName}-VPCPrivateSubnet'

  EFSInterfaceEndpoint:
      Type: 'AWS::EC2::VPCEndpoint'
      Properties:
          VpcEndpointType: Interface
          ServiceName: !Sub 'com.amazonaws.${AWS::Region}.elasticfilesystem'
          VpcId:
            Fn::ImportValue: !Sub '${ApplicationName}-VPC'
          SubnetIds: 
            - Fn::ImportValue: !Sub '${ApplicationName}-VPCPrivateSubnet'
          SecurityGroupIds:
            - !Ref EFSSecurityGroup
Outputs:
  EFS:
    Description: The created EFS 
    Value: !Ref EFSFileSystem
    Export:
      Name: !Sub ${ApplicationName}-EFSFileSystem
  EFSSecurityGroup:
    Description: The EFS SecurityGroup
    Value: !Ref EFSSecurityGroup
    Export:
      Name: !Sub ${ApplicationName}-EFSSecurityGroup
  EFSInterfaceEndpoint:
    Description: The EFS EFSInterfaceEndpoint
    Value: !Ref EFSInterfaceEndpoint
    Export:
      Name: !Sub ${ApplicationName}-EFSInterfaceEndpoint
  EFSMountTarget:
    Description: The EFS EFSMountTarget
    Value: !Ref EFSMountTarget
    Export:
      Name: !Sub ${ApplicationName}-EFSMountTarget
