Resources:
    EFSSecurityGroup:
        Type: "AWS::EC2::SecurityGroup"
        Properties:
            GroupDescription: "security group for the prod EFS"
            GroupName: "test-EFS-SG"
            VpcId: !Ref VPC
            SecurityGroupIngress: 
              - 
                SourceSecurityGroupId: sg-ID
                Description: "servers to connect to efs"
                FromPort: 2049
                IpProtocol: "tcp"
                ToPort: 2049
            Tags:
              - 
                Key: Environment
                Value: prod
              - 
                Key: Name
                Value: test-VPC-EFS-SG
              - 
                Key: Project
                Value: test-blog
              - 
                Key: createdBy
                Value: Maureen Barasa

    EFSFileSystem:
        Type: AWS::EFS::FileSystem
        Properties:
            BackupPolicy:
              Status: ENABLED
            Encrypted: true
            LifecyclePolicies:
              - TransitionToIA: AFTER_60_DAYS
            PerformanceMode: generalPurpose
            Encrypted: true
            ThroughputMode: bursting
            FileSystemTags: 
              - 
                Key: Environment
                Value: test
              - 
                Key: Name
                Value: test-VPC-EFS
              - 
                Key: Project
                Value: test-blog
              - 
                Key: createdBy
                Value: Maureen Barasa

    MountTarget1:
        Type: AWS::EFS::MountTarget
        Properties: 
            FileSystemId: !Ref EFSFileSystem
            IpAddress: *.*.*.*
            SecurityGroups: 
              - !Ref EFSSecurityGroup
            SubnetId: !Ref SubnetID1

Outputs:
  EFS:
    Description: The created EFS 
    Value: !Ref EFSFileSystem

  EFSMountTarget1:
    Description: The EFS MountTarget1
    Value: !Ref MountTarget1
