AWSTemplateFormatVersion: "2010-09-09"
Description: VaultDB Create secure S3 bucket to store data

Parameters:
  ApplicationName:
    Type: String
    AllowedPattern: "^[a-z][a-z0-9-]{0,48}[a-z0-9]$"
    Description: Enter the name of your application with no spaces.

  VPCStackName:
    Type: String
    AllowedPattern: "^[a-z][a-z0-9-]{0,48}[a-z0-9]$"

Metadata:
  Author: VaultDB.ai
  Url: https://vaultdb.ai
  AWS::CloudFormation::Interface: 
    ParameterGroups: 
      - 
        Label: 
          default: "Required Parameters"
        Parameters: 
          - ApplicationName
          - VPCStackName

    ParameterLabels:
      ApplicationName: 
        default: "What are you calling this App(Please Include dev/test/prod in name to diffrentiate between instance)?"
      VPCStackName: 
        default: "What was the name of VPC stack (you should configure network, if not created yet)?"

Rules:
  ApplicationNameIsRequired:
    Assertions:
      - AssertDescription: Application Name is required
        Assert: !Not [!Equals [!Ref ApplicationName, '']]

  VPCStackNameIsRequired:
    Assertions:
      - AssertDescription: VPC Stack name is required
        Assert: !Not [!Equals [!Ref VPCStackName, '']]

Resources:  
  AccessLogBucket:
    Type: "AWS::S3::Bucket"
    Properties:
      AccessControl: LogDeliveryWrite
            
  DataBucket:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: !Join ['', [!Ref ApplicationName, '-vaultdb', '-data']]
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      LoggingConfiguration:
        DestinationBucketName: !Ref AccessLogBucket
        LogFilePrefix: Join ['', [!Ref ApplicationName, '-vaultdb', '-data-store-logs']]

  PublicBucket:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: !Join ['', [!Ref ApplicationName, '-vaultdb', '-public-storage']]
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      LoggingConfiguration:
        DestinationBucketName: !Ref AccessLogBucket
        LogFilePrefix: Join ['', [!Ref ApplicationName, '-vaultdb', '-public-storage-logs']]

  PublicBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref PublicBucket
      PolicyDocument:
        Id: PublicReadPolicy
        Version: 2012-10-17
        Statement:
          - Sid: PublicReadForGetBucketObjects
            Effect: Allow
            Principal: '*'
            Action: 's3:GetObject'
            Resource: !Sub arn:aws:s3:::${PublicBucket}/*

  S3GatewayEndpoint:
    Type: 'AWS::EC2::VPCEndpoint'
    Properties:
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal: '*'
            Action:
              - 's3:*'
            Resource:
              - !Ref DataBucket
              - !Ref PublicBucket
      ServiceName: !Sub 'com.amazonaws.${AWS::Region}.s3'
      VpcId:
        Fn::ImportValue: !Sub "${VPCStackName}-VPC"
      RouteTableIds:
        - Fn::ImportValue: !Sub "${VPCStackName}-PrivateRouteTable"

Outputs:
  DataBucketName:
    Description: Name of the main bucket
    Value: !Ref DataBucket
  LogBucketName:
    Description: Name of the access log bucket
    Value: !Ref AccessLogBucket
