AWSTemplateFormatVersion: "2010-09-09"
Description: Simple cloud formation for bucket creation and configuration

Parameters:
  ApplicationName:
    Type: String
    AllowedPattern: "^[a-z][a-z0-9-]{0,48}[a-z0-9]$"
    Description: Enter the name of your application with no spaces.

  VPCStackName:
    Type: String
    AllowedPattern: "^[a-z][a-z0-9-]{0,48}[a-z0-9]$"

Metadata:
  Author: VaultDB.ai
  Url: https://vaultdb.ai
  AWS::CloudFormation::Interface: 
    ParameterGroups: 
      - 
        Label: 
          default: "Required Parameters"
        Parameters: 
          - ApplicationName
          - VPCStackName

    ParameterLabels:
      ApplicationName: 
        default: "What are you calling this App(Please Include dev/test/prod in name to diffrentiate between instance)?"
      VPCStackName: 
        default: "What was the name of VPC stack (you should configure network, if not created yet)?"

Rules:
  ApplicationNameIsRequired:
    Assertions:
      - AssertDescription: Application Name is required
        Assert: !Equals [!Ref ApplicationName, '']

  VPCStackNameIsRequired:
    Assertions:
      - AssertDescription: VPC Stack name is required
        Assert: !Equals [!Ref VPCStackName, '']

Resources:  
  AccessLogBucket:
    Type: "AWS::S3::Bucket"
    Properties:
      AccessControl: LogDeliveryWrite
            
  PublicBucket:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: !Join ['', [!Ref ApplicationName, '-vaultdb', '-public-storage']]
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      LoggingConfiguration:
        DestinationBucketName: !Ref AccessLogBucket
        LogFilePrefix: Join ['', [!Ref ApplicationName, '-vaultdb', '-public-storage-logs']]

  S3GatewayEndpoint:
    Type: 'AWS::EC2::VPCEndpoint'
    Properties:
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal: '*'
            Action:
              - 's3:GetObject'
            Resource:
              - !Ref PublicBucket
      ServiceName: !Sub 'com.amazonaws.${AWS::Region}.s3'
      VpcId: 
        Fn::ImportValue: !Sub '${VPCStackName}-VPC'
      SubnetIds:
        Fn::ImportValue: !Sub '${VPCStackName}-VPCPrivateSubnetA'

Outputs:
  PublicBucketName:
    Description: Name of the public data and UI content bucket
    Value: !Ref PublicBucket
  LogBucketName:
    Description: Name of the access log bucket
    Value: !Ref AccessLogBucket
