version: '3'

services:
  quickstart:
    # Uncomment the next line to use a non-root user for all processes.
    build: 
      context: .
      dockerfile: dockerfile_lambda
    init: true
    volumes:
      - ..:/workspace:cached
      - vscodeextensions:/.vscode-server/extensions
      - vscodeinsiderextensions:/.vscode-server-insiders/extensions
      - efs:/efs

    command: sleep infinity
    
    environment:
      - Business_Purpose="Development"

    # Uncomment the next four lines if you will use a ptrace-based debuggers like C++, Go, and Rust.
    cap_add:
     - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
volumes:
  vscodeextensions:
  vscodeinsiderextensions:
  efs: