ARG VARIANT="2023-minimal"
FROM public.ecr.aws/lambda/python:3.12

RUN dnf install -y tar gzip

# Add Tini
ENV TINI_VERSION v0.19.0
ADD https://github.com/krallin/tini/releases/download/${TINI_VERSION}/tini /tini
RUN chmod +x /tini

RUN mkdir -p /.vscode-server/extensions
RUN mkdir -p /.vscode-server-insiders/extensions

# Install utilitites
RUN dnf install -y tar gzip

RUN pip3 install ipykernel

ENTRYPOINT ["/tini", "--"]